image: registry.choerodon.com.cn/tools/cifront:0.5.0

stages:
  - node_build
  - docker_build

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

node_build:
  stage: node_build
  script:
    # - node_config
    - node_module
    - node_build
    - cache_dist
  artifacts:
    paths:
    - .auto_devops.sh
  only:
    # - /^release-.*$/
    # - /^hotfix-.*$/
    - master
    # - tags


docker_build:
  image: registry.choerodon.com.cn/tools/cibase:0.5.0
  stage: docker_build
  script:
    - docker_build
    - clean_cache
    - chart_build
  only:
    - master
    # - /^release-.*$/
    # - /^hotfix-.*$/
    # - tags

.auto_devops: &auto_devops |

    # cat "curl -o .auto_devops.sh ${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
    #if [ $? -ne 0 ];then
      cat .auto_devops.sh
      #exit 1
    #fi
    source .auto_devops.sh


    function node_module(){
        mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}

        # npm config set registry https://registry.npm.taobao.org 
        yarn install
    }

    function node_build(){
      # echo ""
      # npm config set registry https://registry.npm.taobao.org 
      # yarn run build
      npm run build
    }

    function cache_dist(){
      cp -r dist /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/dist
      # mv * /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/
    }

    function docker_build(){
        cp -r /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/* ${1:-"."}
        docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"."}
        docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
        echo "${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}"
    }


before_script:
  - *auto_devops
